import type { Note, LibraryItem, Workspace } from '../../../shared/types'
import { hostnameOf, NEWTAB_URL } from './url'

export interface BriefingOptions {
  title: string
  includeTabs: boolean
  includeNotes: boolean
  includeBookmarks: boolean
  notes: Note[]
  bookmarks: LibraryItem[]
  workspace?: Workspace
}

// Compile the user's research (open sources, notes, bookmarks) into a single
// Markdown report — Scout literally "reporting back" what was found.
export function buildBriefing(o: BriefingOptions): string {
  const date = new Date().toLocaleString()
  let md = `# ${o.title}\n\n*Generated by Scout · ${date}*\n`

  if (o.includeTabs && o.workspace) {
    const tabs = o.workspace.tabs.filter((t) => t.url !== NEWTAB_URL)
    if (tabs.length) {
      md += `\n## Open sources — ${o.workspace.name}\n\n`
      for (const t of tabs) md += `- [${t.title || hostnameOf(t.url)}](${t.url})\n`
    }
  }

  if (o.includeNotes) {
    const notes = o.notes
      .filter((n) => n.body.trim())
      .sort((a, b) => b.updatedAt - a.updatedAt)
    if (notes.length) {
      md += `\n## Notes\n`
      for (const n of notes) {
        md += `\n### ${n.title}\n`
        if (n.url) md += `\n*Source: [${hostnameOf(n.url)}](${n.url})*\n`
        md += `\n${n.body.trim()}\n`
      }
    }
  }

  if (o.includeBookmarks) {
    const byCat = new Map<string, LibraryItem[]>()
    for (const b of [...o.bookmarks].sort((a, b) => b.createdAt - a.createdAt)) {
      const arr = byCat.get(b.category) ?? []
      arr.push(b)
      byCat.set(b.category, arr)
    }
    if (byCat.size) {
      md += `\n## Bookmarks\n`
      for (const [cat, items] of byCat) {
        md += `\n### ${cat}\n\n`
        for (const b of items) {
          md += `- [${b.title}](${b.url})${b.description ? ` — ${b.description}` : ''}\n`
        }
      }
    }
  }

  return md.trim() + '\n'
}

export function defaultBriefingTitle(workspace?: Workspace): string {
  const d = new Date().toLocaleDateString(undefined, {
    month: 'short',
    day: 'numeric',
    year: 'numeric'
  })
  return workspace ? `${workspace.name} Briefing — ${d}` : `Scout Briefing — ${d}`
}

export function briefingFilename(title: string): string {
  const slug = title
    .replace(/[^\w\- ]+/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .toLowerCase()
  return `${slug || 'scout-briefing'}.md`
}
